Guest/urls.py
from pydoc import visiblename
from unicodedata import name
from django.urls import path
from Admin.views import acceptdesigner, rejectdesigner

from Guest import views
app_name="Guest"

urlpatterns = [
    path('Newuser/',views.newuser,name="Newuser"),
    path('Newshop/',views.newshop, name="Newshop"),
    path('Newdesigner/',views.newdesigner,name="Newdesigner"),
    path('loadplace/',views.loadplace,name="load-place"),
    path('Login/',views.login,name="Login"), 
    
  
]

Tillage/urls.py
from django.contrib import admin
from django.urls import path,include
from Guest import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Admin/',include("Admin.urls")),
    path('Guest/',include("Guest.urls")),
    path('User/',include("User.urls")),
    path('TillageWizards/',include("TillageWizards.urls")),
    path('Designer/',include("Designer.urls")),
    path('Wizards/',include("Wizards.urls")),
    path('',views.viewhome,name="Viewhome"), 
]
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

TillageWizards/urls.py
from django.urls import path
from Admin.views import medicinecat
from TillageWizards import views

app_name="TillageWizards"


urlpatterns = [
    path('Home/',views.homepage,name="wizards-home"),
    path('myprofile/',views.Myprofile,name="my-profile"),
    path('editprofile/',views.editprofile,name="edit-profile"),
    path('changepassword/',views.changepassword,name="change-password"),
    path('Addproduct/',views.addproduct,name="Add-product"),
    path('Acceptedorder/',views.acceptorder,name="Acceptorder"),
    path('Rejectedorder/',views.rejectorder,name="Rejectorder"),
    path('Addstock/<int:eid>/',views.addstock,name="Add-stock"),
    path('deleteproduct/<int:mid>/',views.delproduct,name="del-product"),
    path('Acceptmedicine/<int:aid>/',views.acceptmedicine,name="Accepted-medicine"),
    path('Rejectedmedicine/<int:rid>/',views.rejectmedicine,name="Rejected-medicine"),
    path('Viewmedicine/',views.viewbookmedicines,name="View-Orders"),
    path('Logout/',views.logout,name="logout"),
    path('Feedback/',views.feedback,name="Feedback-Wizards"),
    path('ViewHelp/',views.viewcompaint,name="View-complaints"),
    path('Accepthelp/<int:aid>/',views.accepthelp,name="Accept-help"),
    path('Rejecthelp/<int:rid>/',views.rejecthelp,name="reject-help"),
    path('Setconsultationfee/<int:cid>/',views.addconsulationfee,name="Set-Consultationfee"),
    path('Complaintshop/',views.complaintshop,name="shop-complaints"),
    path('Viewcomplaintshop/',views.viewcomplaintwizard,name="viewshop-complaints"),
    path('Viewcomplaintuser/',views.viewcomplaintusertoshop,name="viewuser-complaints"),
    path('Replycomplaintuser/',views.viewcomplaintusertoshop,name="Replyuser-complaints"),
]

User/urls.py
from django.urls import path

from User import views

app_name="User"


urlpatterns = [
    path('Home/',views.homepage,name="User-Home"),
    path('myprofile/',views.Myprofile,name="my-profile"),
    path('editprofile/',views.editprofile,name="edit-profile"),
    path('changepassword/',views.changepassword,name="change-password"),
    path('Addsalesproduct/',views.product,name="Add-product"),
    path('Addstock/<int:eid>/',views.addstock,name="Add-stock"),
    path('Viewproduct/',views.viewbookproduct,name="View-product"),
    path('Viewbookmedicine/',views. viewmyordermedicines,name="View-bookmedicine"),
    path('Viewbookproduct/',views. viewmyproductorder,name="View-bookproduct"),
    path('Acceptedproduct/<int:psid>/',views.acceptedorder,name="Accepted-order"),
    path('Rejectedproduct/<int:rid>/',views.rejectedorder,name="Rejected-order"),
    path('deleteproduct/<int:pid>/',views.delproduct,name="del-product"),
    path('Searchproduct/',views.searchproduct,name="Search-product"),
    path('Searchmedicine/',views.searchmedicine,name="Search-medicine"),
    path('Searchservices/',views.searchservice,name="Search-services"),
    path('Viewmoreservices/<int:sid>/',views.viewmoreservice,name="viewmore-services"),
    path('Viewmoreproduct/<int:pid>/',views.viewmoreproduct,name="viewmore-product"),
    path('Viewmoremedicine/<int:mid>/',views.viewmoremedicine,name="viewmore-medicine"),
    path('Buyproduct/<int:bpid>/',views.buyproduct,name="Buy-product"),
    path('Buymedicine/<int:bmid>/',views.buymedicine,name="Buy-medicine"),
    path('Contactservice/<int:csid>/',views.contactservice,name="Contact-service"),
    path('Payment/<int:bmid>/',views.payment,name="Pay-now"),
    path('Paymentpro/<int:bpid>/',views.paymentpro,name="Pay-nowpro"),
    path('Logout/',views.logout,name="logout"),
    path('Feedback/',views.feedback,name="Send Feedback"),
    path('Help/<int:wid>/',views.help,name="help-help"),
    path('Complaintuser/',views.complaintuser,name="send-complaint"),
    path('Viewcomplaintuser/',views.viewmycomplaint,name="Viewuser-complaint"),
    path('Complaintproduct/<int:pcid>/',views.complaintproduct,name="Send-productcomplaint"),
    path('Complaintusertoshop/<int:usid>/',views.complaintusertoshop,name="Send-shopcomplaint"),
    path('Complaintusertodesigner/<int:udid>/',views.complaintusertodesigner,name="Send-designercomplaint"),
    path('Replayusertouser/<int:rpid>/',views.replyusertouser,name="Reply-usercomplaint"),
    path('Chats/<int:cid>/',views.Chat,name="Consultations"),
    path('Loadchat/',views.loadchat,name="loadchat"),
    path('Date/<int:bid>/',views.deliveringdate,name="Delivering date"),
    path('Viewwizard/',views.viewwizard,name="View-wizard"),






]

TillageWizards/models.py
from django.db import models
from Admin.models import Medicinecategory

from Guest.models import Newshop, Newuser

# Create your models here.
class NewMedicine(models.Model):
    name=models.CharField(max_length=50)
    rate=models.CharField(max_length=50)
    details=models.CharField(max_length=80)
    stock=models.IntegerField()
    photo=models.ImageField(upload_to='uploads/medicineimages/')
    doj=models.DateField(auto_now_add=True)
    shop=models.ForeignKey(Newshop,on_delete=models.CASCADE)
    cat=models.ForeignKey(Medicinecategory,on_delete=models.CASCADE,null=True)
    

class Feedbackshop(models.Model):
    doc=models.DateField(auto_now_add=True)
    wizards=models.ForeignKey(Newshop,on_delete=models.CASCADE)
    Feedback=models.TextField(max_length=50)

class Complaintshop(models.Model):
    content=models.TextField(max_length=100)
    shop=models.ForeignKey(Newshop,on_delete=models.CASCADE,null=True)
    attachment=models.FileField(upload_to='uploads/complaintshopimages/')
    vstatus=models.IntegerField(default=False)
    replay=models.TextField(max_length=100,default="noreply")
    doc=models.DateField(auto_now_add=True)

TillageWizards/views.py
from django.shortcuts import redirect, render
from Admin.models import Medicinecategory

from Guest.models import Newshop
from TillageWizards.models import  Complaintshop, Feedbackshop, NewMedicine
from User.models import Bookmedicine, Complaintusertoshop, Help
from django.conf import settings
from django.core.mail import send_mail
# Create your views here.


def homepage(request):
    if 'shopid' in request.session:
        return render(request,'TillageWizards/Home.html')
    else:
        return redirect('Guest:Login')

def Myprofile(request):
    if 'shopid' in request.session:
        wizardobj=Newshop.objects.get(id=request.session["shopid"])
        return render(request,'TillageWizards/Myprofile.html',{"shop":wizardobj})
    else:
        return redirect('Guest:Login')

def editprofile(request):
    if 'shopid' in request.session:
        wizardobj=Newshop.objects.get(id=request.session["shopid"])
        if request.method=='POST' and request.FILES:
            name=request.POST.get("name")
            contact=request.POST.get("contact")
            address=request.POST.get("address")
            logo=request.FILES.get("logo")
            wizardobj.name=name
            wizardobj.contact=contact
            wizardobj.address=address
            wizardobj.logo=logo
            wizardobj.save()
            return redirect('TillageWizards:my-profile')
        else:
            return render(request,'TillageWizards/Editprofile.html',{"shop":wizardobj})
    else:
        return redirect('Guest:Login')


def changepassword(request):
    if 'shopid' in request.session:
        wizardobj=Newshop.objects.get(id=request.session["shopid"])
        if request.method=='POST':
            passs=wizardobj.password
            cpass=request.POST.get("currentpassword")
            npass=request.POST.get("newpassword")
            if passs==cpass:
                wizardobj.password=npass
                wizardobj.save()
                return redirect('Guest:Login')
            else:
                pass
        else:
            return render(request,'TillageWizards/Changepassword.html')
    else:
        return redirect('Guest:Login')


def addproduct(request):
    if 'shopid' in request.session:
        pro=NewMedicine.objects.all()
        dis=Medicinecategory.objects.all()
        if request.method=='POST'and request.FILES:
            name=request.POST.get("productname")
            rate=request.POST.get("rate")
            details=request.POST.get("details")
            stock1=request.POST.get("stock")
            img=request.FILES.get("photo")
            cat=request.POST.get("medicinecategory")
            catobj=Medicinecategory.objects.get(id=cat)
            probj=Newshop.objects.get(id=request.session["shopid"])
            NewMedicine.objects.create(name=name,rate=rate,details=details,stock=stock1,shop=probj,photo=img,cat=catobj)
            return render(request,'TillageWizards/Newproduct.html',{"name":pro,"dis":dis})
        else:
            return render(request,'TillageWizards/Newproduct.html',{"name":pro,"dis":dis})
    else:
        return redirect('Guest:Login')


def delproduct(request,mid):
    if 'shopid' in request.session:
        pl=NewMedicine.objects.get(id=mid)
        pl.delete()
        return redirect("TillageWizards:Add-product")
    else:
        return redirect('Guest:Login')

def addstock(request,eid):
    if 'shopid' in request.session:
        pro=NewMedicine.objects.get(id=eid)
        if request.method=='POST':
            stock1=int(request.POST.get("stock"))
            oldstock=int(pro.stock)
            newstock=stock1+oldstock
            pro.stock=newstock
            pro.save()  
            return redirect("TillageWizards:Add-product") 
        else:
            return render(request,'TillageWizards/Addstock.html')
    else:
        return redirect('Guest:Login')


def viewbookmedicines(request):
    if 'shopid' in request.session:
        med=Bookmedicine.objects.filter(vstatus=0)
        return render(request,'TillageWizards/Orders.html',{"medicine":med})
    else:
        return redirect('Guest:Login')


def acceptmedicine(request,aid):
    if 'shopid' in request.session:
        medobj=Bookmedicine.objects.get(id=aid)
        email1=medobj.user.email
        name=medobj.user.name
        obj=medobj.medicine.id
        newobj=NewMedicine.objects.get(id=obj)
        stock1=int(newobj.stock)
        quan=int(medobj.quantity)
        bal=stock1-quan
        newobj.stock=bal
        medobj.vstatus='1'
        send_mail(
            'Respected sir/madam '+name, #subject
            "\ryour booking is Successfully completed welcome to Tillage.\n Your delivery is expected in 7 workingdays.\n This is from Tillage team thank you for our booking service. \r\n If you have any questions and if there is anything we can improve please reply to this email. \r\n we were always happy to help!. \r\n \r\n Team Tillage.\n Thank you.",#body
            settings.EMAIL_HOST_USER,
            [email1],

        )
        medobj.save()
        newobj.save()
        return redirect('/TillageWizards/Orders/')
    else:
        return redirect('Guest:Login')

def rejectmedicine(request,rid):
    if 'shopid' in request.session:
        medobj=Bookmedicine.objects.get(id=rid)
        email1=medobj.user.email
        name=medobj.user.name
        medobj.vstatus='2'
        send_mail(
            'Respected sir/madam '+name, #subject
            "\rsorry your booking process is Failed\nSorry to inform that you failed in the booking process .\n This is from Tillage team thank you for our booking service. \r\n If you have any questions and if there is anything we can improve please reply to this email. \r\n we were always happy to help!. \r\n \r\n Team Tillage.\n Thank you.",#body
            settings.EMAIL_HOST_USER,
            [email1],

        )
        medobj.save()
        return redirect('/TillageWizards/Viewmedicine/')
    else:
        return redirect('Guest:Login')


def acceptorder(request):
    if 'shopid' in request.session:
        ac=Bookmedicine.objects.filter(vstatus=1)
        return render(request,'TillageWizards/Acceptedorder.html',{"medicine":ac})
    else:
        return redirect('Guest:Login')


def rejectorder(request):
    if 'shopid' in request.session:
        ac=Bookmedicine.objects.filter(vstatus=2)
        return render(request,'TillageWizards/Rejectedorder.html',{"medicine":ac})
    else:
        return redirect('Guest:Login')

def feedback(request):
    if 'shopid' in request.session:
        
        shopobj=Newshop.objects.get(id=request.session["shopid"])
        if request.method=='POST':
            feed=request.POST.get("feedback")
            Feedbackshop.objects.create(Feedback=feed,user=shopobj)
            return render(request,'/TillageWizards/Home/')
        else:
         return render(request,'TillageWizards/Feedbackshop.html')
    else:
        return redirect('Guest:Login')

def logout(request):
    del request.session['shopid']
    return redirect('Guest:Login')

def viewcompaint(request):
    if 'shopid' in request.session:
        com=Help.objects.all()
        return render(request,'TillageWizards/Viewcomplaints.html',{"complaints":com})
    else:
        return redirect('Guest:Login')

def accepthelp(request,aid):
    if 'shopid' in request.session:
        comobj=Help.objects.get(id=aid)
        email1=comobj.user.email
        name=comobj.user.name
        comobj.vstatus='1'
        send_mail(
            'Respected sir/madam '+name, #subject
            "\rWelcome our helpline service.\n Your complaint is verified and we will respond after fewhours.\n This is from Tillage team thank you for our helpline service. \r\n If you have any questions and if there is anything we can improve please reply to this email. \r\n we were always happy to help!. \r\n \r\n Team Tillage.\n Thank you.",#body
            settings.EMAIL_HOST_USER,
            [email1],

        )
        comobj.save()
        return redirect('TillageWizards:View-complaints')
    else:
        return redirect('Guest:Login')


def rejecthelp(request,rid):
    if 'shopid' in request.session:
        comobj=Help.objects.get(id=rid)
        email1=comobj.user.email
        name=comobj.user.name
        comobj.vstatus='2'
        send_mail(
            'Respected sir/madam '+name, #subject
            "\rwelcome our helpline service\nyour complaint is verified your disease is not detected so we will respond after 7workingdays.\n This is from Tillage team thank you for our helpline service. \r\n If you have any questions and if there is anything we can improve please reply to this email. \r\n we were always happy to help!. \r\n \r\n Team Tillage.\n Thank you.",#body
            settings.EMAIL_HOST_USER,
            [email1],

        )
        comobj.save()
        return redirect('TillageWizards:View-complaints')
    else:
        return redirect('Guest:Login')

def addconsulationfee(request,cid):
    if 'shopid' in request.session:
        pro=Help.objects.get(id=cid)
        if request.method=='POST':
            rate=int(request.POST.get("consultationfee"))
            pro.stock=rate
            pro.save()  
            return redirect('TillageWizards:View-complaints')
        else:
            return render(request,'TillageWizards/Consultationfee.html')
    else:
        return redirect('Guest:Login')

def complaintshop(request):
    if 'shopid' in request.session:
        shopobj=Newshop.objects.get(id=request.session["shopid"])
        if request.method=='POST'and request.FILES:
            con=request.POST.get("content")
            att=request.FILES.get("attachment")
            Complaintshop.objects.create(content=con,attachment=att,shop=shopobj)
            return redirect('/TillageWizards/Home/')
        else:
            return render(request,'TillageWizards/complaintshop.html')
    else:
        return redirect('Guest:Login')

def viewcomplaintwizard(request):

TillageWizards/templates/TillageWizards/Addstock.html
{% extends 'TillageWizards/Head.html' %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="tab">
        <br><br><br><br><br><br><br><br><br>
    <form method="post">
        {% csrf_token %}
        <table border="2" cellspadding="10" align="center">
            <tr>
                <th>Stock</th>
                <td>
                    <input type="text" name="stock" required autocomplete="off">
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" name="btnsubmit" value="save">
                    <input type="reset" name="btncancel" value="cancel">
                </td>
            </tr>
        </table>
    </form>
    </div>
</body>
</html>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

TillageWizards/templates/TillageWizards/Head.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Tillage</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="{% static 'Main/assets/img/favicon.png' %}">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/all.min.css' %}">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'Main/assets/bootstrap/css/bootstrap.min.css' %}">
	<!-- owl carousel -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/owl.carousel.css' %}">
	<!-- magnific popup -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/magnific-popup.css' %}">
	<!-- animate css -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/animate.css' %}">
	<!-- mean menu css -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/meanmenu.min.css' %}">
	<!-- main style -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/main.css' %}">
	<!-- responsive -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/responsive.css' %}">
	<!-- form.css -->
	<link rel="stylesheet" href="{% static 'form.css' %}">

</head>
<body>
	
	<!--PreLoader-->
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    <!--PreLoader Ends-->
	
	<!-- header -->
	<div class="top-header-area" id="sticker" style="background-color: #051922;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="{% url 'Viewhome' %}">
								<div class="title"><p style="font-size:40px; color: brown;">Tillage</p></div> 
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li class="current-list-item"><a href="{% url 'TillageWizards:Tillagewizards-home' %}">Home</a>
									<!-- <ul class="sub-menu">
										<li><a href="index.html">Static Home</a></li>
										<li><a href="index_2.html">Slider Home</a></li>
									</ul> -->
								</li>
								 
								<li><a href="">Privacy</a>
									<ul class="sub-menu">
										<li><a href="{% url 'TillageWizards:my-profile' %}">Myprofile</a></li>
										<li><a href="{% url 'TillageWizards:edit-profile' %}">Editprofile</a></li>
										<li><a href="{% url 'TillageWizards:change-password' %}">Changepassword</a></li>
										<!-- <li><a href="checkout.html">Check Out</a></li>
										<li><a href="contact.html">Contact</a></li>
										<li><a href="news.html">News</a></li>
										<li><a href="shop.html">Shop</a></li> -->
									</ul>
								</li>
								<li><a href="">Medicine</a>
									<ul class="sub-menu">
										<li><a href="{% url 'TillageWizards:Add-product' %}">Add Medicine</a></li>
										<!-- <li><a href="single-news.html">Single News</a></li> -->
									</ul>
								</li> 
								<!-- <li><a href="{% url 'Guest:Login' %}">Login</a></li> -->
								<li><a href="">Orders</a>
									<ul class="sub-menu">
										<li><a href="{% url 'TillageWizards:View-Orders' %}">Mange Orders</a></li>
										<!-- <li><a href="{% url 'Guest:Newuser' %}">User</a></li>
										 <li><a href="{% url 'Guest:Newdesigner' %}">Single Product</a></li>
										<li><a href="cart.html">Cart</a></li> --> 
									</ul>
								</li>
								<li><a href="">Feedback</a>
									<ul class="sub-menu">
								<li><a href="{% url 'TillageWizards:Feedback-Wizards' %}">View Feedback</a></li>
							</ul>
						</li>
						<li><a href="">Complaints</a>
							<ul class="sub-menu">
						<li><a href="{% url 'TillageWizards:shop-complaints' %}">Send Complaints</a></li>
						<li><a href="{% url 'TillageWizards:viewshop-complaints' %}">ViewMy Complaints</a></li>
                        <li><a href="{% url 'TillageWizards:viewuser-complaints' %}">ViewUser Complaints</a></li>
					</ul>
				</li>
				<li><a href="{%  url 'TillageWizards:logout' %}">Logout</a></li>
								
						<!-- <a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div> -->
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->
	
	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search area -->

    {% block content %}


    {% endblock %}

    	<!-- footer -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-box about-widget">
						<h2 class="widget-title">About us</h2>
						<p>Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box get-in-touch">
						<h2 class="widget-title">Get in Touch</h2>
						<ul>
							<li>34/8, East Hukupara, Gifirtok, Sadan.</li>
							<li>support@fruitkha.com</li>
							<li>+00 111 222 3333</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box pages">
						<h2 class="widget-title">Pages</h2>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><a href="services.html">Shop</a></li>
							<li><a href="news.html">News</a></li>
							<li><a href="contact.html">Contact</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box subscribe">
						<h2 class="widget-title">Subscribe</h2>
						<p>Subscribe to our mailing list to get the latest updates.</p>
						<form action="index.html">
							<input type="email" placeholder="Email">
							<button type="submit"><i class="fas fa-paper-plane"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end footer -->
	
	<!-- copyright -->
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<p>Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>,  All Rights Reserved.<br>
						Distributed By - <a href="https://themewagon.com/">Themewagon</a>
					</p>
				</div>
				<div class="col-lg-6 text-right col-md-12">
					<div class="social-icons">
						<ul>
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end copyright -->
	
	<!-- jquery -->
	<script src="{% static 'Main/assets/js/jquery-1.11.3.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'Main/assets/bootstrap/js/bootstrap.min.js' %}"></script>
	<!-- count down -->
	<script src="{% static 'Main/assets/js/jquery.countdown.js' %}"></script>
	<!-- isotope -->
	<script src="{% static 'Main/assets/js/jquery.isotope-3.0.6.min.js' %}"></script>
	<!-- waypoints -->
	<script src="{% static 'Main/assets/js/waypoints.js' %}"></script>
	<!-- owl carousel -->
	<script src="{% static 'Main/assets/js/owl.carousel.min.js' %}"></script>
	<!-- magnific popup -->
	<script src="{% static 'Main/assets/js/jquery.magnific-popup.min.js' %}"></script>
	<!-- mean menu -->
	<script src="{% static 'Main/assets/js/jquery.meanmenu.min.js' %}"></script>
	<!-- sticker js -->
	<script src="{% static 'Main/assets/js/sticker.js' %}"></script>
	<!-- main js -->
	<script src="{% static 'Main/assets/js/main.js' %}"></script>

</body>
</html>

TillageWizards/templates/TillageWizards/Homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hii</h1>
    <a href="{%  url 'TillageWizards:my-profile' %}">My Profile</a>
    <a href="{%  url 'TillageWizards:edit-profile' %}">edit Profile</a>
    <a href="{%  url 'TillageWizards:change-password' %}">change password</a>
    <a href="{%  url 'TillageWizards:Add-product' %}">Add product</a>
    <a href="{%  url 'TillageWizards:View-Orders' %}">View Orders</a>
    <a href="{%  url 'TillageWizards:Feedback-Wizards' %}">Send feedback</a>
    <a href="{%  url 'TillageWizards:shop-complaints' %}">Send complaints </a>
    <a href="{%  url 'TillageWizards:viewshop-complaints' %}">viewmy complaints </a>
    <a href="{%  url 'TillageWizards:viewuser-complaints' %}">viewuser complaints </a>
    <a href="{%  url 'TillageWizards:logout' %}">Logout</a>
</body>
</html>