Guest/urls.py
from pydoc import visiblename
from unicodedata import name
from django.urls import path
from Admin.views import acceptdesigner, rejectdesigner

from Guest import views
app_name="Guest"

urlpatterns = [
    path('Newuser/',views.newuser,name="Newuser"),
    path('Newshop/',views.newshop, name="Newshop"),
    path('Newdesigner/',views.newdesigner,name="Newdesigner"),
    path('loadplace/',views.loadplace,name="load-place"),
    path('Login/',views.login,name="Login"), 
    
  
]

Tillage/urls.py
from django.contrib import admin
from django.urls import path,include
from Guest import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Admin/',include("Admin.urls")),
    path('Guest/',include("Guest.urls")),
    path('User/',include("User.urls")),
    path('TillageWizards/',include("TillageWizards.urls")),
    path('Designer/',include("Designer.urls")),
    path('Wizards/',include("Wizards.urls")),
    path('',views.viewhome,name="Viewhome"), 
]
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path

from User import views

app_name="User"


urlpatterns = [
    path('Home/',views.homepage,name="User-Home"),
    path('myprofile/',views.Myprofile,name="my-profile"),
    path('editprofile/',views.editprofile,name="edit-profile"),
    path('changepassword/',views.changepassword,name="change-password"),
    path('Addsalesproduct/',views.product,name="Add-product"),
    path('Addstock/<int:eid>/',views.addstock,name="Add-stock"),
    path('Viewproduct/',views.viewbookproduct,name="View-product"),
    path('Viewbookmedicine/',views. viewmyordermedicines,name="View-bookmedicine"),
    path('Viewbookproduct/',views. viewmyproductorder,name="View-bookproduct"),
    path('Acceptedproduct/<int:psid>/',views.acceptedorder,name="Accepted-order"),
    path('Rejectedproduct/<int:rid>/',views.rejectedorder,name="Rejected-order"),
    path('deleteproduct/<int:pid>/',views.delproduct,name="del-product"),
    path('Searchproduct/',views.searchproduct,name="Search-product"),
    path('Searchmedicine/',views.searchmedicine,name="Search-medicine"),
    path('Searchservices/',views.searchservice,name="Search-services"),
    path('Viewmoreservices/<int:sid>/',views.viewmoreservice,name="viewmore-services"),
    path('Viewmoreproduct/<int:pid>/',views.viewmoreproduct,name="viewmore-product"),
    path('Viewmoremedicine/<int:mid>/',views.viewmoremedicine,name="viewmore-medicine"),
    path('Buyproduct/<int:bpid>/',views.buyproduct,name="Buy-product"),
    path('Buymedicine/<int:bmid>/',views.buymedicine,name="Buy-medicine"),
    path('Contactservice/<int:csid>/',views.contactservice,name="Contact-service"),
    path('Payment/<int:bmid>/',views.payment,name="Pay-now"),
    path('Paymentpro/<int:bpid>/',views.paymentpro,name="Pay-nowpro"),
    path('Logout/',views.logout,name="logout"),
    path('Feedback/',views.feedback,name="Send Feedback"),
    path('Help/<int:wid>/',views.help,name="help-help"),
    path('Complaintuser/',views.complaintuser,name="send-complaint"),
    path('Viewcomplaintuser/',views.viewmycomplaint,name="Viewuser-complaint"),
    path('Complaintproduct/<int:pcid>/',views.complaintproduct,name="Send-productcomplaint"),
    path('Complaintusertoshop/<int:usid>/',views.complaintusertoshop,name="Send-shopcomplaint"),
    path('Complaintusertodesigner/<int:udid>/',views.complaintusertodesigner,name="Send-designercomplaint"),
    path('Replayusertouser/<int:rpid>/',views.replyusertouser,name="Reply-usercomplaint"),
    path('Chats/<int:cid>/',views.Chat,name="Consultations"),
    path('Loadchat/',views.loadchat,name="loadchat"),
    path('Date/<int:bid>/',views.deliveringdate,name="Delivering date"),
    path('Viewwizard/',views.viewwizard,name="View-wizard"),






]

Wizards/urls.py
from django.urls import path

from Wizards import views

app_name="Wizards"


urlpatterns = [
    path('Home/',views.homepage,name="WizardsHome"),
    path('myprofile/',views.Myprofile,name="my-profile"),
    path('Editprofile/',views.editprofile,name="Edit-profile"),
    path('Changepassword/',views.changepassword,name="Change-password"),
    path('Viewcomplaint/',views.viewcompaint,name="View-complaint"),
    path('Accepthelp/<int:aid>/',views.accepthelp,name="Accept-Help"),
    path('Rejecthelp/<int:rid>/',views.rejecthelp,name="Reject-Help"),
    path('ViewAccepthelp/',views.viewaccepthelp,name="ViewAccept-Help"),
    path('ViewRejecthelp/',views.viewrejecthelp,name="ViewReject-Help"),
    path('Logout/',views.logout,name="Logout"),
    path('Chats/<int:cid>/',views.Chat,name="Chat-User"),
    path('Loadchat/',views.loadchat,name="loadchat"),
    

]

Wizards/models.py
from django.db import models

# Create your models here.

Wizards/views.py
from django.shortcuts import render,redirect

from Admin.models import Wizards
from Guest.models import Newuser
from User.models import Help, chat
from django.conf import settings
from django.core.mail import send_mail
# Create your views here.

def homepage(request):
    if 'wizardid' in request.session:
        return render(request,'Wizards/Home.html')
    else:
        return redirect('Guest:Login')


def Myprofile(request):
    if 'wizardid' in request.session:
        wizardobj=Wizards.objects.get(id=request.session["wizardid"])
        return render(request,'Wizards/Myprofile.html',{"wizard":wizardobj})
    else:
        return redirect('Guest:Login')

def editprofile(request):
        wizardobj=Wizards.objects.get(id=request.session["wizardid"])
        if request.method=='POST':
            name=request.POST.get("name")
            contact=request.POST.get("contact")
            address=request.POST.get("address")
            wizardobj.name=name
            wizardobj.contact=contact
            wizardobj.address=address
            wizardobj.save()
            return redirect('Wizard:my-profile')
        else:
            return render(request,'Wizards/Editprofile.html',{"user":wizardobj})

def changepassword(request):
    # if 'userid' in request.session:
        wizardobj=Wizards.objects.get(id=request.session["wizardid"])
        if request.method=='POST':
            passs=wizardobj.password
            cpass=request.POST.get("currentpassword")
            npass=request.POST.get("newpassword")
            if passs==cpass:
                wizardobj.password=npass
                wizardobj.save()
                return redirect('Guest:Login')
            else:
                pass
        else:
            return render(request,'Wizards/Changepassword.html')
    # else:
    #     return redirect('Guest:Login')


def viewcompaint(request):
    # if 'shopid' in request.session:
        com=Help.objects.all()
        return render(request,'Wizards/Viewcomplaints.html',{"complaints":com})
    # else:
    #     return redirect('Guest:Login')

def accepthelp(request,aid):
    # if 'shopid' in request.session:
        comobj=Help.objects.get(id=aid)
        email1=comobj.user.email
        name=comobj.user.name
        comobj.vstatus='1'
        send_mail(
            'Respected sir/madam '+name, #subject
            "\rWelcome our helpline service.\n Your complaint is verified and we will respond after fewhours.\n This is from Tillage team thank you for our helpline service. \r\n If you have any questions and if there is anything we can improve please reply to this email. \r\n we were always happy to help!. \r\n \r\n Team Tillage.\n Thank you.",#body
            settings.EMAIL_HOST_USER,
            [email1],

        )
        comobj.save()
        return redirect('Wizards:View-complaint')
    # else:
    #     return redirect('Guest:Login')


def rejecthelp(request,rid):
    # if 'shopid' in request.session:
        comobj=Help.objects.get(id=rid)
        email1=comobj.user.email
        name=comobj.user.name
        comobj.vstatus='2'
        send_mail(
            'Respected sir/madam '+name, #subject
            "\rwelcome our helpline service\nyour complaint is verified your disease is not detected so we will respond after 7workingdays.\n This is from Tillage team thank you for our helpline service. \r\n If you have any questions and if there is anything we can improve please reply to this email. \r\n we were always happy to help!. \r\n \r\n Team Tillage.\n Thank you.",#body
            settings.EMAIL_HOST_USER,
            [email1],

        )
        comobj.save()
        return redirect('Wizards:View-complaint')
    # else:
    #     return redirect('Guest:Login')



def viewaccepthelp(request):
    # if 'adminid' in request.session:
        acuser=Help.objects.filter(vstatus=1)
        return render(request,'wizards/Acceptedhelp.html',{"user":acuser})
    # else:
    #     return redirect('Guest:Login')


def viewrejecthelp(request):
    # if 'adminid' in request.session:
        acuser=Help.objects.filter(vstatus=2)
        return render(request,'wizards/Rejectedhelp.html',{"user":acuser})
    # else:
    #     return redirect('Guest:Login')

def logout(request):
    del request.session['wizardid']
    return redirect('Guest:Login')


def Chat(request, cid):
    chatobj = Help.objects.get(id=cid)
    if request.method == "POST":
        cied = request.POST.get("cid")
        # print(cied)
        ciedobj = Newuser.objects.get(id=cied)
        sobj = Wizards.objects.get(id=request.session["wizardid"])
        content = request.POST.get("msg")
        # print(cied)
        print(content)
        chat.objects.create(
            from_user=None, to_wizards=None, content=content, to_user=ciedobj, from_wizards=sobj)
        return render(request, 'Wizards/Chat.html', {"chatobj": chatobj})
    else:
        return render(request, 'Wizards/Chat.html', {"chatobj": chatobj})


def loadchat(request):
    cid = request.GET.get("cid")
    request.session["cid"] = cid

    cid1 = request.session["cid"]
    # print(cid1)

    # print(cid)
    shopobj = Newuser.objects.get(id=cid)
    # print(userobj)
    sid = request.session["wizardid"]
    # print(sid)
    suserobj = Wizards.objects.get(id=request.session["wizardid"])
    # chatobj1 = Chat.objects.filter(Q(to_user=suserobj) | Q(
    #     from_user=suserobj), Q(to_shop=shopobj) | Q(from_shop=shopobj))
    # print(chatobj1)  # send message
    li = [cid, cid]
    # print(chatobj2)  # recived msg
    chatobj = chat.objects.raw(
        "select * from User_chat c inner join Admin_wizards u on (u.id=c.from_wizards_id) or (u.id=c.to_wizards_id) WHERE  c.from_user_id=%s or c.to_user_id=%s order by c.date", params=[(cid1), (cid1)])

    print(chatobj.query)

    return render(request, 'Wizards/Load.html', {"obj": chatobj, "sid": sid, "shop": shopobj, "userobj": suserobj})

Wizards/templates/Wizards/Acceptedhelp.html
{% extends 'Wizards/Head.html' %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="tab" style="width: 100%;padding-left:100px;">
        <br><br><br><br><br><br>
        <h3 style="padding-left: 550px; "><b>Accept Help</b></h3>
    <form method="post">
        <table border="2" width="350px" style="background-color: violet;" align="center">

            <tr style="background-color: rgb(7, 163, 20);">
                <th>Name</th>
                <th>Contact</th>
                <th>Email</th>
                <th>Address</th>
                <th>Place</th>
                <th>Pincode</th>
                <th>District</th>
                <th colspan="2">Action</th>
            </tr>
            {% for x in user %}
            <tr>
                <td>{{ x.user.name }}</td>
                <td>{{ x.user.contact }}</td>
                <td>{{ x.user.email}}</td>
                <td>{{ x.user.address }}</td>
                <td>{{ x.user.place.place }}</td>
                <td>{{ x.user.place.pincode }}</td>
                <td>{{ x.user.place.district.district }}</td>
                <td>
                    
                    <a href="{% url 'Wizards:Reject-Help' x.id %}">Reject</a>
                <p> <a href="{% url 'Wizards:Chat-User' x.id %}">Chat Now</a></p>
                </td>
            </tr>
            {% endfor %}

        </table>
    </form>
    </div>
</body>
</html>
<br><br><br><br><br><br><br><br><br>
{% endblock %}

Wizards/templates/Wizards/Changepassword.html
{% extends 'Wizards/Head.html' %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="tab" style="width: 100%;padding-left:100px;">
        <br><br><br><br><br><br>
        <h3 style="padding-left: 500px; "><b>Changepassword</b></h3>
    <form method="post">
        <table border="2" width="350px" style="background-color: violet;" align="center">            <tr>
                <th>Currentpassword</th>
                    <td>
                        <input type="password" name="currentpassword">
                    </td>
            </tr>
            <tr>
                <th>Newpassword</th>
                <td>
                    <input type="password" name="newpassword">
                </td>
            </tr>
            <tr>
                <th>confirmpassword</th>
                <td>
                    <input type="password" name="confirmpassword" onblur="return checkpwd(newpassword,this)">
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" name="btnsave" value="save">
                    <input type="reset" name="btncancel" value="cancel"
                </td>
            </tr>
        </table>
    </form>
    </div>
</body>
<script>
    
function checkpwd(confirm, pass) {
    if(confirm.value != pass.value){
        alert("password Mismatch")
        return false
    }
    else{
        return true
    }
    }

</script>
</html>
<br><br>
{% endblock %}

Wizards/templates/Wizards/Head.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Tillage</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="{% static 'Main/assets/img/favicon.png' %}">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/all.min.css' %}">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'Main/assets/bootstrap/css/bootstrap.min.css' %}">
	<!-- owl carousel -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/owl.carousel.css' %}">
	<!-- magnific popup -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/magnific-popup.css' %}">
	<!-- animate css -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/animate.css' %}">
	<!-- mean menu css -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/meanmenu.min.css' %}">
	<!-- main style -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/main.css' %}">
	<!-- responsive -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/responsive.css' %}">
	<!-- form.css -->
	<link rel="stylesheet" href="{% static 'form.css' %}">

</head>
<body>
	
	<!--PreLoader-->
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    <!--PreLoader Ends-->
	
	<!-- header -->
	<div class="top-header-area" id="sticker" style="background-color: #051922;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="{% url 'Viewhome' %}">
								<div class="title"><p style="font-size:40px; color: rgb(248, 244, 244);"><b>TILLAGE</b></p></div> 
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li class="current-list-item"><a href="{% url 'Wizards:WizardsHome' %}">Home</a>
									<!-- <ul class="sub-menu">
										<li><a href="index.html">Static Home</a></li>
										<li><a href="index_2.html">Slider Home</a></li>
									</ul> -->
								</li>
								<!-- <li><a href="about.html">About</a></li>
								<li><a href="#">Pages</a>
									<ul class="sub-menu">
										<li><a href="404.html">404 page</a></li>
										<li><a href="about.html">About</a></li>
										<li><a href="cart.html">Cart</a></li>
										<li><a href="checkout.html">Check Out</a></li>
										<li><a href="contact.html">Contact</a></li>
										<li><a href="news.html">News</a></li>
										<li><a href="shop.html">Shop</a></li>
									</ul>
								</li>
								<li><a href="news.html">News</a>
									<ul class="sub-menu">
										<li><a href="news.html">News</a></li>
										<li><a href="single-news.html">Single News</a></li>
									</ul>
								</li> -->
								
								<li><a href="">Privacy</a>
									<ul class="sub-menu">
										<!-- <li><a href="shop.html">Designer</a></li> -->
										<li><a href="{%  url 'Wizards:my-profile' %}">Myprofile</a></li>
									    <li><a href="{%  url 'Wizards:Edit-profile' %}">Editprofile</a></li>
										<li><a href="{%  url 'Wizards:Change-password' %}">Changepassword</a></li>
									</ul>
								</li>
								
									
										<li><a href="{%  url 'Wizards:View-complaint' %}">View Consultation</a></li>
								
										<li><a href="{%  url 'Wizards:ViewAccept-Help' %}">View Accept</a></li>
									    <li><a href="{%  url 'Wizards:ViewReject-Help' %}">View Reject</a></li>
										<li><a href="{%  url 'Wizards:Logout' %}">Logout</a></li>
									
													
						
						<!-- <a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div> -->
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->
	
	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search area -->

    {% block content %}


    {% endblock %}

    	<!-- footer -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-box about-widget">
						<h2 class="widget-title">About us</h2>
						<p>Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box get-in-touch">
						<h2 class="widget-title">Get in Touch</h2>
						<ul>
							<li>34/8, East Hukupara, Gifirtok, Sadan.</li>
							<li>support@fruitkha.com</li>
							<li>+00 111 222 3333</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box pages">
						<h2 class="widget-title">Pages</h2>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><a href="services.html">Shop</a></li>
							<li><a href="news.html">News</a></li>
							<li><a href="contact.html">Contact</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box subscribe">
						<h2 class="widget-title">Subscribe</h2>
						<p>Subscribe to our mailing list to get the latest updates.</p>
						<form action="index.html">
							<input type="email" placeholder="Email">
							<button type="submit"><i class="fas fa-paper-plane"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end footer -->
	
	<!-- copyright -->
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<p>Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>,  All Rights Reserved.<br>
						Distributed By - <a href="https://themewagon.com/">Themewagon</a>
					</p>
				</div>
				<div class="col-lg-6 text-right col-md-12">
					<div class="social-icons">
						<ul>
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end copyright -->
	
	<!-- jquery -->
	<script src="{% static 'Main/assets/js/jquery-1.11.3.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'Main/assets/bootstrap/js/bootstrap.min.js' %}"></script>
	<!-- count down -->
	<script src="{% static 'Main/assets/js/jquery.countdown.js' %}"></script>
	<!-- isotope -->
	<script src="{% static 'Main/assets/js/jquery.isotope-3.0.6.min.js' %}"></script>
	<!-- waypoints -->
	<script src="{% static 'Main/assets/js/waypoints.js' %}"></script>
	<!-- owl carousel -->
	<script src="{% static 'Main/assets/js/owl.carousel.min.js' %}"></script>
	<!-- magnific popup -->
	<script src="{% static 'Main/assets/js/jquery.magnific-popup.min.js' %}"></script>
	<!-- mean menu -->
	<script src="{% static 'Main/assets/js/jquery.meanmenu.min.js' %}"></script>
	<!-- sticker js -->
	<script src="{% static 'Main/assets/js/sticker.js' %}"></script>
	<!-- main js -->
	<script src="{% static 'Main/assets/js/main.js' %}"></script>

</body>
</html>

Wizards/templates/Wizards/Homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <h1>Hii</h1> 
   
   <a href="{%  url 'Wizards:my-profile' %}">My Profile</a>
   <a href="{%  url 'Wizards:Edit-profile' %}">Edit Profile</a>
   <a href="{%  url 'Wizards:Change-password' %}">Changepassword</a>
   <a href="{%  url 'Wizards:View-complaint' %}">Viewcomplaint</a>
   <a href="{%  url 'Wizards:ViewAccept-Help' %}">ViewAccepthelp</a>
   <a href="{%  url 'Wizards:ViewReject-Help' %}">ViewRejectcomplaint</a>
   <a href="{%  url 'Wizards:Logout' %}">Logout</a>
</body>
</html>

Wizards/templates/Wizards/Rejectedhelp.html
{% extends 'Wizards/Head.html' %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="tab" style="width: 100%;padding-left:100px;">
        <br><br><br><br><br><br>
        <h3 style="padding-left: 550px; "><b>Reject Help</b></h3>
    <form method="post">
        <table border="2" width="350px" style="background-color: violet;" align="center">

            <tr style="background-color: rgb(7, 163, 20);">
                <th>Name</th>
                <th>Contact</th>
                <th>Email</th>
                <th>Address</th>
                <th>Place</th>
                <th>Pincode</th>
                <th>District</th>
                <th colspan="2">Action</th>
            </tr>
            {% for x in user %}
            <tr>
                <td>{{ x.user.name }}</td>
                <td>{{ x.user.contact }}</td>
                <td>{{ x.user.email}}</td>
                <td>{{ x.user.address }}</td>
                <td>{{ x.user.place.place }}</td>
                <td>{{ x.user.place.pincode }}</td>
                <td>{{ x.user.place.district.district }}</td>
                <td><a href="{% url 'Wizards:Accept-Help' x.id %}">Accept</a></td>
            </tr>
            {% endfor %}

        </table>
    </form>
    </div>
</body>
</html>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

Wizards/templates/Wizards/Viewcomplaints.html
{% extends 'Wizards/Head.html' %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="tab" style="width: 100%;padding-left:100px;">
        <br><br><br><br><br><br>
        <h3 style="padding-left: 550px; "><b>ViewComplaints</b></h3>
    <form method="post">
        <table border="2" width="350px" style="background-color: violet;" align="center">
            <tr style="background-color: rgb(7, 163, 20);">
                <th>User</th>
                <th>Contact</th>
                <th>Email</th>
                <th>Place</th>
                <th>Date</th>
                <th>Title</th>
                <th>Photo</th>
                <th>Discription</th>
                <th colspan="">Action</th>

            </tr>
            {%  for i in complaints %}
            <tr>
                <td>{{i.user.name}}</td>
                <td>{{i.user.contact}}</td>
                <td>{{i.user.email}}</td>
                <td>{{i.user.place.place}}</td>
                <td>{{i.doc}}</td>
                <td>{{i.title}}</td>
                <td><img src="{{i.photo.url}}" width="100" height="100"></td>
                <td>{{i.discription}}</td>

                <td>
                    {% if i.vstatus == 0 %}
                    <a href="{% url 'Wizards:Accept-Help' i.id %}">Accept</a>
                    <a href="{% url 'Wizards:Reject-Help' i.id %}">Reject</a>
                    {% elif i.vstatus == 1 %}
                   
                    <a href="">Chat Now</a>
                    {% else %}
                    <p>Rejected..</p>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </form>
    </div>
</body>
</html>
<br><br><br><br><br><br><br><br><br>
{% endblock %}