Guest/urls.py
from pydoc import visiblename
from unicodedata import name
from django.urls import path
from Admin.views import acceptdesigner, rejectdesigner

from Guest import views
app_name="Guest"

urlpatterns = [
    path('Newuser/',views.newuser,name="Newuser"),
    path('Newshop/',views.newshop, name="Newshop"),
    path('Newdesigner/',views.newdesigner,name="Newdesigner"),
    path('loadplace/',views.loadplace,name="load-place"),
    path('Login/',views.login,name="Login"), 
    
  
]

Tillage/urls.py
from django.contrib import admin
from django.urls import path,include
from Guest import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Admin/',include("Admin.urls")),
    path('Guest/',include("Guest.urls")),
    path('User/',include("User.urls")),
    path('TillageWizards/',include("TillageWizards.urls")),
    path('Designer/',include("Designer.urls")),
    path('Wizards/',include("Wizards.urls")),
    path('',views.viewhome,name="Viewhome"), 
]
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path

from User import views

app_name="User"


urlpatterns = [
    path('Home/',views.homepage,name="User-Home"),
    path('myprofile/',views.Myprofile,name="my-profile"),
    path('editprofile/',views.editprofile,name="edit-profile"),
    path('changepassword/',views.changepassword,name="change-password"),
    path('Addsalesproduct/',views.product,name="Add-product"),
    path('Addstock/<int:eid>/',views.addstock,name="Add-stock"),
    path('Viewproduct/',views.viewbookproduct,name="View-product"),
    path('Viewbookmedicine/',views. viewmyordermedicines,name="View-bookmedicine"),
    path('Viewbookproduct/',views. viewmyproductorder,name="View-bookproduct"),
    path('Acceptedproduct/<int:psid>/',views.acceptedorder,name="Accepted-order"),
    path('Rejectedproduct/<int:rid>/',views.rejectedorder,name="Rejected-order"),
    path('deleteproduct/<int:pid>/',views.delproduct,name="del-product"),
    path('Searchproduct/',views.searchproduct,name="Search-product"),
    path('Searchmedicine/',views.searchmedicine,name="Search-medicine"),
    path('Searchservices/',views.searchservice,name="Search-services"),
    path('Viewmoreservices/<int:sid>/',views.viewmoreservice,name="viewmore-services"),
    path('Viewmoreproduct/<int:pid>/',views.viewmoreproduct,name="viewmore-product"),
    path('Viewmoremedicine/<int:mid>/',views.viewmoremedicine,name="viewmore-medicine"),
    path('Buyproduct/<int:bpid>/',views.buyproduct,name="Buy-product"),
    path('Buymedicine/<int:bmid>/',views.buymedicine,name="Buy-medicine"),
    path('Contactservice/<int:csid>/',views.contactservice,name="Contact-service"),
    path('Payment/<int:bmid>/',views.payment,name="Pay-now"),
    path('Paymentpro/<int:bpid>/',views.paymentpro,name="Pay-nowpro"),
    path('Logout/',views.logout,name="logout"),
    path('Feedback/',views.feedback,name="Send Feedback"),
    path('Help/<int:wid>/',views.help,name="help-help"),
    path('Complaintuser/',views.complaintuser,name="send-complaint"),
    path('Viewcomplaintuser/',views.viewmycomplaint,name="Viewuser-complaint"),
    path('Complaintproduct/<int:pcid>/',views.complaintproduct,name="Send-productcomplaint"),
    path('Complaintusertoshop/<int:usid>/',views.complaintusertoshop,name="Send-shopcomplaint"),
    path('Complaintusertodesigner/<int:udid>/',views.complaintusertodesigner,name="Send-designercomplaint"),
    path('Replayusertouser/<int:rpid>/',views.replyusertouser,name="Reply-usercomplaint"),
    path('Chats/<int:cid>/',views.Chat,name="Consultations"),
    path('Loadchat/',views.loadchat,name="loadchat"),
    path('Date/<int:bid>/',views.deliveringdate,name="Delivering date"),
    path('Viewwizard/',views.viewwizard,name="View-wizard"),






]

User/views.py
from turtle import title
from django.shortcuts import redirect, render
from Admin.models import Category, Medicinecategory, Wizards
from Designer.models import Services
from django.conf import settings
from django.core.mail import send_mail
from Guest.models import Newdeigner, Newshop, Newuser
from TillageWizards.models import  Complaintshop, NewMedicine
from User.models import Bookmedicine, Bookproduct, Complaintproduct, Complaintuser, Complaintusertodesigner, Complaintusertoshop, Feedbackuser, Help, Newproduct, chat

# Create your views here.


def homepage(request):
    if 'userid' in request.session:
        return render(request,'User/Home.html')
    else:
        return redirect('Guest:Login')

def Myprofile(request):
    if 'userid' in request.session:
        userobj=Newuser.objects.get(id=request.session["userid"])
        return render(request,'User/Myprofile.html',{"user":userobj})
    else:
        return redirect('Guest:Login')


def editprofile(request):
    if 'userid' in request.session:
        userobj=Newuser.objects.get(id=request.session["userid"])
        if request.method=='POST':
            name=request.POST.get("name")
            contact=request.POST.get("contact")
            address=request.POST.get("address")
            userobj.name=name
            userobj.contact=contact
            userobj.address=address
            userobj.save()
            return redirect('User:my-profile')
        else:
            return render(request,'User/Editprofile.html',{"user":userobj})
    else:
        return redirect('Guest:Login')


def changepassword(request):
    if 'userid' in request.session:
        userobj=Newuser.objects.get(id=request.session["userid"])
        if request.method=='POST':
            passs=userobj.password
            cpass=request.POST.get("currentpassword")
            npass=request.POST.get("newpassword")
            if passs==cpass:
                userobj.password=npass
                userobj.save()
                return redirect('Guest:Login')
            else:
                pass
        else:
            return render(request,'User/Changepassword.html')
    else:
        return redirect('Guest:Login')

        
def product(request):
    if 'userid' in request.session:
        dis=Category.objects.all()
        pro=Newproduct.objects.all()
        if request.method=='POST'and request.FILES:
            name=request.POST.get("productname")
            rate=request.POST.get("rate")
            
            stock1=request.POST.get("stock")
            img=request.FILES.get("photo")
            probj=Newuser.objects.get(id=request.session["userid"])
            Newproduct.objects.create(name=name,rate=rate,stock=stock1,user=probj,photo=img)
            return render(request,'User/Newproduct.html',{"name":pro,"dis":dis})
        else:
            return render(request,'User/Newproduct.html',{"name":pro,"dis":dis})
    else:
        return redirect('Guest:Login')

def delproduct(request,pid):
    if 'userid' in request.session:
        pl=Newproduct.objects.get(id=pid)
        pl.delete()
        return redirect("User:Add-product")
    else:
        return redirect('Guest:Login')

def addstock(request,eid):
    if 'userid' in request.session:
        pro=Newproduct.objects.get(id=eid)
        if request.method=='POST':
            stock1=int(request.POST.get("stock"))
            oldstock=int(pro.stock)
            newstock=stock1+oldstock
            pro.stock=newstock
            pro.save()  
            return redirect("User:Add-product") 
        else:
            return render(request,'User/Addstock.html')
    else:
        return redirect('Guest:Login')

def searchproduct(request):
    if 'userid' in request.session:
        dis=Category.objects.all()
        userobj=Newuser.objects.get(id=request.session["userid"])
        pro=Newproduct.objects.all()
        if request.method=='POST':
            category1=request.POST.get("category")
            print(category1)
            catobj=Category.objects.get(id=category1)
            pro=Newproduct.objects.filter(cat=catobj)
            print(pro)
            return render(request,'User/Searchproduct.html',{"name":pro,"dis":dis})
        else:
            return render(request,'User/Searchproduct.html',{"name":pro,"dis":dis})
    else:
        return redirect('Guest:Login')

def searchmedicine(request):
    if 'userid' in request.session:
        med=Medicinecategory.objects.all()
        print(med)
        pro=NewMedicine.objects.all()
        if request.method=='POST':
            category1=request.POST.get("medicinecategory")
            print(category1)
            catobj=Medicinecategory.objects.get(id=category1)
            pro=NewMedicine.objects.filter(cat=catobj)
            print(pro)
            return render(request,'User/Searchmedicine.html',{"name":pro,"med":med})
        else:
            return render(request,'User/Searchmedicine.html',{"name":pro,"med":med})
    else:
        return redirect('Guest:Login')

def searchservice(request):
    if 'userid' in request.session:
        mo=Services.objects.all()
        print(mo)
        return render(request,'User/Searchservices.html',{"name":mo})
    else:
        return redirect('Guest:Login')


def viewmoreservice(request,sid):
    if 'userid' in request.session:
        mo=Services.objects.get(id=sid)
        return render(request,'User/Viewmoreservices.html',{"name":mo})
    else:
        return redirect('Guest:Login')


def viewmoreproduct(request,pid):
    if 'userid' in request.session:
        mo=Newproduct.objects.get(id=pid)
        return render(request,'User/Viewmoreproduct.html',{"name":mo})
    else:
        return redirect('Guest:Login')

def viewmoremedicine(request,mid):
    if 'userid' in request.session:
        mo=NewMedicine.objects.get(id=mid)
        return render(request,'User/Viewmoremedicine.html',{"name":mo})
    else:
        return redirect('Guest:Login')

def buyproduct(request,bpid):
    if 'userid' in request.session:
        mo=Newproduct.objects.get(id=bpid)
        userobj=Newuser.objects.get(id=request.session["userid"])
        if request.method=='POST':
            quan=request.POST.get("quantity")
            ship=request.POST.get("shippingcharge")
            topr=request.POST.get("totalprice")
            Bookproduct.objects.create(quantity=quan,totalprice=topr,user=userobj,product=mo,shipment=ship)
            return render(request,'User/Buyproduct.html',{"name":mo,"user":userobj})
        else:
            return render(request,'User/Buyproduct.html',{"name":mo,"user":userobj})
    else:
        return redirect('Guest:Login')
    
    
def buymedicine(request,bmid):
    if 'userid' in request.session:
        mo=NewMedicine.objects.get(id=bmid)
        userobj=Newuser.objects.get(id=request.session["userid"])
        if request.method=='POST':
            quan=request.POST.get("quantity")
            topr=request.POST.get("totalprice")
            Bookmedicine.objects.create(quantity=quan,totalprice=topr,user=userobj,medicine=mo)
            return render(request,'User/Buymedicine.html',{"name":mo,"user":userobj})
        else:
         return render(request,'User/Buymedicine.html',{"name":mo,"user":userobj})
    else:
        return redirect('Guest:Login')
    

def contactservice(request,csid):
    if 'userid' in request.session:
        mo=Services.objects.get(id=csid)
        return render(request,'User/Contactservice.html',{"name":mo})
    else:
        return redirect('Guest:Login')



def viewbookproduct(request):
    if 'userid' in request.session:
        med=Bookproduct.objects.filter(product__user=request.session["userid"])
        return render(request,'User/Orders.html',{"product":med})
    else:
        return redirect('Guest:Login')


def acceptedorder(request,psid):
    if 'userid' in request.session:
        medobj=Bookproduct.objects.get(id=psid)
        print(medobj)
        email1=medobj.user.email
        name=medobj.user.name
        obj=medobj.product.id
        newobj=Newproduct.objects.get(id=obj)
        stock1=int(newobj.stock)
        quan=int(medobj.quantity)
        bal=stock1-quan
        newobj.stock=bal
        medobj.vstatus='1'
        send_mail(
            'Respected sir/madam '+name, #subject
            "\ryour booking is Successfully completed welcome to Tillage.\n Your delivery is expected in 7 workingdays.\n This is from Tillage team thank you for our booking service. \r\n If you have any questions and if there is anything we can improve please reply to this email. \r\n we were always happy to help!. \r\n \r\n Team Tillage.\n Thank you.",#body
            settings.EMAIL_HOST_USER,
            [email1],

        )
        medobj.save()
        newobj.save()
        return redirect('/User/Viewproduct/')
    else:
        return redirect('Guest:Login')



def rejectedorder(request,rid):
    if 'userid' in request.session:
        medobj=Bookproduct.objects.get(id=rid)
        email1=medobj.user.email
        name=medobj.user.name
        medobj.vstatus='2'
        send_mail(
            'Respected sir/madam '+name, #subject
            "\rsorry your booking process is Failed\nSorry to inform that you failed in the booking process .\n This is from Tillage team thank you for our booking service. \r\n If you have any questions and if there is anything we can improve please reply to this email. \r\n we were always happy to help!. \r\n \r\n Team Tillage.\n Thank you.",#body
            settings.EMAIL_HOST_USER,
            [email1],

        )
        medobj.save()
        return redirect('/User/Viewproduct/')
    else:
        return redirect('Guest:Login')


def acceptorder(request):
    if 'userid' in request.session:
        ac=Bookproduct.objects.filter(vstatus=1)
        return render(request,'User/Acceptedorder.html',{"product":ac})
    else:
        return redirect('Guest:Login')

def rejectorder(request):
    if 'userid' in request.session:

User/templates/User/Head.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Tillage</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="{% static 'Main/assets/img/favicon.png' %}">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/all.min.css' %}">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'Main/assets/bootstrap/css/bootstrap.min.css' %}">
	<!-- owl carousel -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/owl.carousel.css' %}">
	<!-- magnific popup -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/magnific-popup.css' %}">
	<!-- animate css -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/animate.css' %}">
	<!-- mean menu css -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/meanmenu.min.css' %}">
	<!-- main style -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/main.css' %}">
	<!-- responsive -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/responsive.css' %}">
	<!-- form.css -->
	<link rel="stylesheet" href="{% static 'form.css' %}">

</head>
<body>
	
	<!--PreLoader-->
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    <!--PreLoader Ends-->
	
	<!-- header -->
	<div class="top-header-area" id="sticker" style="background-color: #051922;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="{% url 'Viewhome' %}">
								<div class="title"><p style="font-size:40px; color: rgb(247, 245, 245);">Tillage</p></div> 
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li class="current-list-item"><a href="{% url 'User:User-Home' %}">Home</a>
									<!-- <ul class="sub-menu">
										<li><a href="index.html">Static Home</a></li>
										<li><a href="index_2.html">Slider Home</a></li>
									</ul> -->
								</li>
								<!-- <li><a href="about.html">About</a></li>
								<li><a href="#">Pages</a>
									<ul class="sub-menu">
										<li><a href="404.html">404 page</a></li>
										<li><a href="about.html">About</a></li>
										<li><a href="cart.html">Cart</a></li>
										<li><a href="checkout.html">Check Out</a></li>
										<li><a href="contact.html">Contact</a></li>
										<li><a href="news.html">News</a></li>
										<li><a href="shop.html">Shop</a></li>
									</ul>
								</li>
								<li><a href="news.html">News</a>
									<ul class="sub-menu">
										<li><a href="news.html">News</a></li>
										<li><a href="single-news.html">Single News</a></li>
									</ul>
								</li> -->
								
								<li><a href="">Privacy</a>
									<ul class="sub-menu">
										<!-- <li><a href="shop.html">Designer</a></li> -->
										<li><a href="{% url 'User:my-profile' %}">Myprofile</a></li>
									    <li><a href="{% url 'User:edit-profile' %}">Editprofile</a></li>
										<li><a href="{% url 'User:change-password' %}">Changepassword</a></li>
									</ul>
								</li>
								<li><a href="{%  url 'User:View-product' %}">Orders</a></li>
								<li><a href="">Products</a>
									<ul class="sub-menu">
									
										<li><a href="{% url 'User:Add-product' %}">Add Products</a></li>
										
									    </ul>
								</li>
								<li><a href="">Search</a>
									<ul class="sub-menu">
										<!-- <li><a href="shop.html">Designer</a></li> -->
										<li><a href="{% url 'User:Search-product' %}">Search Product</a></li>
									    <li><a href="{% url 'User:Search-medicine' %}">Search Medicine</a></li>
										<li><a href="{% url 'User:Search-services' %}">Search services</a></li>
									</ul>
								</li>
								<li><a href="">Bookings</a>
									<ul class="sub-menu">
										<!-- <li><a href="shop.html">Designer</a></li> -->
										<li><a href="{% url 'User:View-bookproduct' %}">Book Products</a></li>
									    <li><a href="{% url 'User:View-bookmedicine' %}">Book Medicines</a></li>
										
									</ul>
								</li>
								<li><a href="">Feedback</a>
									<ul class="sub-menu">
										<!-- <li><a href="shop.html">Designer</a></li> -->
										<li><a href="{% url 'User:Send Feedback' %}">Send Feedback</a></li>
									    
									</ul>
								</li>
								<li><a href="{%  url 'User:View-wizard' %}">View Consultation</a></li>
								<li><a href="">Complaints</a>
									<ul class="sub-menu">
										
										<li><a href="{% url 'User:send-complaint' %}">Send AdminComplaint</a></li>
										<li><a href="{% url 'User:Viewuser-complaint' %}">View MyComplaint</a></li>
									</ul>
								</li> 
								<li><a href="{%  url 'User:logout' %}">Logout</a></li>
								
						<!-- <a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div> -->
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->
	
	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search area -->

    {% block content %}


    {% endblock %}

    	<!-- footer -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-box about-widget">
						<h2 class="widget-title">About us</h2>
						<p>Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box get-in-touch">
						<h2 class="widget-title">Get in Touch</h2>
						<ul>
							<li>34/8, East Hukupara, Gifirtok, Sadan.</li>
							<li>support@fruitkha.com</li>
							<li>+00 111 222 3333</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box pages">
						<h2 class="widget-title">Pages</h2>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><a href="services.html">Shop</a></li>
							<li><a href="news.html">News</a></li>
							<li><a href="contact.html">Contact</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box subscribe">
						<h2 class="widget-title">Subscribe</h2>
						<p>Subscribe to our mailing list to get the latest updates.</p>
						<form action="index.html">
							<input type="email" placeholder="Email">
							<button type="submit"><i class="fas fa-paper-plane"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end footer -->
	
	<!-- copyright -->
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<p>Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>,  All Rights Reserved.<br>
						Distributed By - <a href="https://themewagon.com/">Thresiamma Mathew</a>
					</p>
				</div>
				<div class="col-lg-6 text-right col-md-12">
					<div class="social-icons">
						<ul>
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end copyright -->
	
	<!-- jquery -->
	<script src="{% static 'Main/assets/js/jquery-1.11.3.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'Main/assets/bootstrap/js/bootstrap.min.js' %}"></script>
	<!-- count down -->
	<script src="{% static 'Main/assets/js/jquery.countdown.js' %}"></script>
	<!-- isotope -->
	<script src="{% static 'Main/assets/js/jquery.isotope-3.0.6.min.js' %}"></script>
	<!-- waypoints -->
	<script src="{% static 'Main/assets/js/waypoints.js' %}"></script>
	<!-- owl carousel -->
	<script src="{% static 'Main/assets/js/owl.carousel.min.js' %}"></script>
	<!-- magnific popup -->
	<script src="{% static 'Main/assets/js/jquery.magnific-popup.min.js' %}"></script>
	<!-- mean menu -->
	<script src="{% static 'Main/assets/js/jquery.meanmenu.min.js' %}"></script>
	<!-- sticker js -->
	<script src="{% static 'Main/assets/js/sticker.js' %}"></script>
	<!-- main js -->
	<script src="{% static 'Main/assets/js/main.js' %}"></script>

</body>
</html>

User/templates/User/Homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hii</h1>

    <a href="{%  url 'User:my-profile' %}">My Profile</a>
    <a href="{%  url 'User:edit-profile' %}">edit Profile</a>
    <a href="{%  url 'User:change-password' %}">change password</a>
    <a href="{%  url 'User:View-wizard' %}">View wizard</a>
    <a href="{%  url 'User:Add-product' %}">Add product</a>
    <a href="{%  url 'User:Search-product' %}">Search-product</a>
    <a href="{%  url 'User:Search-medicine' %}">Search Medicine</a>
    <a href="{%  url 'User:Search-services' %}">Search services</a>
    <a href="{%  url 'User: View-product' %}">Orders</a>
    <a href="{%  url 'User:View-bookmedicine' %}">My bookmedicine</a>
    <a href="{%  url 'User:View-bookproduct' %}">My bookproduct</a>
    <a href="{%  url 'User:View-product' %}">View bookings</a>
    <a href="{%  url 'User:Send Feedback' %}">Send Feedback</a>
    <a href="{%  url 'User:View-wizard' %}">View Consultation</a>
    <a href="{%  url 'User:send-complaint' %}">send complaint</a>
    <a href="{%  url 'User:Viewuser-complaint' %}">Viewmy complaint</a>
    <a href="{%  url 'User:Delivering date' %}">Delivering Date</a>
    <a href="{%  url 'User:logout' %}">Logout</a>
  
</body>
</html>

User/templates/User/Mymedicineorder.html
{% extends 'User/Head.html' %}


{% block content %}<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div id="tab" style="width: 100%;padding-left:100px;">
        <br><br><br><br><br><br>
        <h3 style="padding-left: 550px; "><b>My Bookmedicine</b></h3>
    <form method="post">
        <table border="2" width="350px" style="background-color: violet;" align="center">
            <tr style="background-color: rgb(7, 163, 20);">

                <th>Photo</th>
                <th>Name</th>
                <th>Rate</th>
                <th>Details</th>
                <th>Quantity</th>
                <th>Bookingdate</th>
                <th>Totalprice</th>
                <th>Delivering</th>
                <th>Action</th>
            </tr>

            {% for x in medicine %}
            <tr>
               <td> <img src="{{x.medicine.photo.url}}" width="120" height="120">
            </td>
            <td>{{ x.medicine.name}} </td>
            <td>{{ x.medicine.rate }} </td>
            <td>{{ x.medicine.details}} </td>
            <td>{{ x.quantity}} </td>
            <td>{{x.doj}} </td>
            <td>{{ x.totalprice}} </td>
            <td>{{ x.delivering}} </td>
            <td>
                <a href="{% url 'User:Send-shopcomplaint' x.medicine.shop.id %}">Send shopcomplaint </a>

            {% if x.vstatus == 1 %}
            {% if x.pstatus == 0%}
            <a href="{% url 'User:Pay-now' x.id %}">Pay Now</a>
            {% elif x.pstatus == 1 %}
            <p>Paid..</p>
            {% endif %}
            {% elif x.vstatus == 2 %}
            <p>Rejected</p>
            {% else %}
            <p>Pending..</p>
            {% endif %}
        </td>
            </tr>

            {% endfor %}
            
        </table>

    </form>
    </div>
</body>

</html>
<br><br><br>  <br><br><br>  <br><br><br>  <br><br><br>  <br><br><br>

{% endblock %}

User/templates/User/Viewmoreservices.html
{% extends 'User/Head.html' %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="tab">
        <br><br><br>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <br>
    <hr>
    <br>
    <table align="center">
        <tr>

           
            <td>
                <p style="border:1px solid black; align-items: center;">
                    <img src="{{name.logo.url}}" width="120" height="120"><br>
                    {{ name.name}}<br>
                    {{ name.rate }}<br>
                    {{ name.details}}<br>
                    <a href="{% url 'User:Contact-service' name.id %}">Contact services</a>
                </p>
            </td>

         
        </tr>
    </table>
</form>
    </div>
</body>
</html>
<br><br><br>

{% endblock %}