Designer/urls.py
from django.urls import path

from Designer import views


app_name="Designer"


urlpatterns = [
    path('Home/',views.homepage,name="Designer-Home"),
    path('myprofile/',views.Myprofile,name="my-profile"),
    path('editprofile/',views.editprofile,name="edit-profile"),
    path('changepassword/',views.changepassword,name="change-password"),  
    path('Services/',views.services,name="Add-Services"),
    path('DelServices/<int:mid>/',views.delservice,name="del-Services"),
    path('Logout/',views.logout,name="logout"),
    path('Feedback/',views.feedback,name="Feedback Designer"),
    path('Complaintdesigner/',views.complaintdesigner,name="Complaint Designer"),
    path('Viewcomplaintdesigner/',views.viewcomplaintdesigner,name="Viewcomplaint Designer"),
    path('Viewusercomplaint/',views.viewcomplaintuserdesigner,name="Viewcomplaint user"),
    path('Replyusercomplaint/<int:rdid>/',views.replyusertodesigner,name="Replycomplaint user"),



]

Guest/urls.py
from pydoc import visiblename
from unicodedata import name
from django.urls import path
from Admin.views import acceptdesigner, rejectdesigner

from Guest import views
app_name="Guest"

urlpatterns = [
    path('Newuser/',views.newuser,name="Newuser"),
    path('Newshop/',views.newshop, name="Newshop"),
    path('Newdesigner/',views.newdesigner,name="Newdesigner"),
    path('loadplace/',views.loadplace,name="load-place"),
    path('Login/',views.login,name="Login"), 
    
  
]

Tillage/urls.py
from django.contrib import admin
from django.urls import path,include
from Guest import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Admin/',include("Admin.urls")),
    path('Guest/',include("Guest.urls")),
    path('User/',include("User.urls")),
    path('TillageWizards/',include("TillageWizards.urls")),
    path('Designer/',include("Designer.urls")),
    path('Wizards/',include("Wizards.urls")),
    path('',views.viewhome,name="Viewhome"), 
]
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path

from User import views

app_name="User"


urlpatterns = [
    path('Home/',views.homepage,name="User-Home"),
    path('myprofile/',views.Myprofile,name="my-profile"),
    path('editprofile/',views.editprofile,name="edit-profile"),
    path('changepassword/',views.changepassword,name="change-password"),
    path('Addsalesproduct/',views.product,name="Add-product"),
    path('Addstock/<int:eid>/',views.addstock,name="Add-stock"),
    path('Viewproduct/',views.viewbookproduct,name="View-product"),
    path('Viewbookmedicine/',views. viewmyordermedicines,name="View-bookmedicine"),
    path('Viewbookproduct/',views. viewmyproductorder,name="View-bookproduct"),
    path('Acceptedproduct/<int:psid>/',views.acceptedorder,name="Accepted-order"),
    path('Rejectedproduct/<int:rid>/',views.rejectedorder,name="Rejected-order"),
    path('deleteproduct/<int:pid>/',views.delproduct,name="del-product"),
    path('Searchproduct/',views.searchproduct,name="Search-product"),
    path('Searchmedicine/',views.searchmedicine,name="Search-medicine"),
    path('Searchservices/',views.searchservice,name="Search-services"),
    path('Viewmoreservices/<int:sid>/',views.viewmoreservice,name="viewmore-services"),
    path('Viewmoreproduct/<int:pid>/',views.viewmoreproduct,name="viewmore-product"),
    path('Viewmoremedicine/<int:mid>/',views.viewmoremedicine,name="viewmore-medicine"),
    path('Buyproduct/<int:bpid>/',views.buyproduct,name="Buy-product"),
    path('Buymedicine/<int:bmid>/',views.buymedicine,name="Buy-medicine"),
    path('Contactservice/<int:csid>/',views.contactservice,name="Contact-service"),
    path('Payment/<int:bmid>/',views.payment,name="Pay-now"),
    path('Paymentpro/<int:bpid>/',views.paymentpro,name="Pay-nowpro"),
    path('Logout/',views.logout,name="logout"),
    path('Feedback/',views.feedback,name="Send Feedback"),
    path('Help/<int:wid>/',views.help,name="help-help"),
    path('Complaintuser/',views.complaintuser,name="send-complaint"),
    path('Viewcomplaintuser/',views.viewmycomplaint,name="Viewuser-complaint"),
    path('Complaintproduct/<int:pcid>/',views.complaintproduct,name="Send-productcomplaint"),
    path('Complaintusertoshop/<int:usid>/',views.complaintusertoshop,name="Send-shopcomplaint"),
    path('Complaintusertodesigner/<int:udid>/',views.complaintusertodesigner,name="Send-designercomplaint"),
    path('Replayusertouser/<int:rpid>/',views.replyusertouser,name="Reply-usercomplaint"),
    path('Chats/<int:cid>/',views.Chat,name="Consultations"),
    path('Loadchat/',views.loadchat,name="loadchat"),
    path('Date/<int:bid>/',views.deliveringdate,name="Delivering date"),
    path('Viewwizard/',views.viewwizard,name="View-wizard"),






]

Designer/models.py
from django.db import models

from Guest.models import Newdeigner, Newuser

# Create your models here.

class Services(models.Model):
    name=models.CharField(max_length=50)
    rate=models.CharField(max_length=50)
    details=models.CharField(max_length=80)
    logo=models.FileField(upload_to='uploads/serviceimages/')
    design=models.ForeignKey(Newdeigner,on_delete=models.CASCADE)
    
    

class Feedbackdesigner(models.Model):
    doc=models.DateField(auto_now_add=True)
    designer=models.ForeignKey(Newdeigner,on_delete=models.CASCADE)
    Feedback=models.TextField(max_length=50)

class Complaintdesigner(models.Model):
    content=models.TextField(max_length=100)
    designer=models.ForeignKey(Newdeigner,on_delete=models.CASCADE,null=True)
    attachment=models.FileField(upload_to='uploads/complaintimages/')
    vstatus=models.IntegerField(default=False)
    replay=models.TextField(max_length=100,default="noreply")
    doc=models.DateField(auto_now_add=True)

Designer/views.py
from django.shortcuts import redirect, render
from Designer.models import  Complaintdesigner, Feedbackdesigner, Services

from Guest.models import Newdeigner
from User.models import Complaintusertodesigner

# Create your views here.
def homepage(request):
    if 'desiid' in request.session:
        return render(request,'Designer/Home.html')
    else:
        return redirect('Guest:Login')

def Myprofile(request):
    if 'desiid' in request.session:
        desiobj=Newdeigner.objects.get(id=request.session["desiid"])
        return render(request,'Designer/Myprofile.html',{"designer":desiobj})
    else:
        return redirect('Guest:Login')

def editprofile(request):
    if 'desiid' in request.session:
        desiobj=Newdeigner.objects.get(id=request.session["desiid"])
        if request.method=='POST' and request.FILES:
            name=request.POST.get("name")
            contact=request.POST.get("contact")
            address=request.POST.get("address")
            logo=request.FILES.get("logo")
            desiobj.name=name
            desiobj.contact=contact
            desiobj.address=address
            desiobj.logo=logo
            desiobj.save()
            return redirect('Designer:my-profile')
        else:
            return render(request,'Designer/Editprofile.html',{"designer":desiobj})
    else:
        return redirect('Guest:Login')


def changepassword(request):
    if 'desiid' in request.session:
        desiobj=Newdeigner.objects.get(id=request.session["desiid"])
        if request.method=='POST':
            passs=desiobj.password
            cpass=request.POST.get("currentpassword")
            npass=request.POST.get("newpassword")
            if passs==cpass:
                desiobj.password=npass
                desiobj.save()
                return redirect('Guest:Login')
            else:
                pass
        else:
            return render(request,'Designer/Changepassword.html')
    else:
        return redirect('Guest:Login')


def services(request):
    if 'desiid' in request.session:
        pro=Services.objects.all()
        if request.method=='POST'and request.FILES:
            name=request.POST.get("modelname")
            rate=request.POST.get("rate")
            details=request.POST.get("details")
            img=request.FILES.get("photo")
            probj=Newdeigner.objects.get(id=request.session["desiid"])
            Services.objects.create(name=name,rate=rate,details=details,design=probj,logo=img)
            return render(request,'Designer/Newservices.html',{"name":pro})
        else:
            return render(request,'Designer/Newservices.html',{"name":pro})
    else:
        return redirect('Guest:Login')

def delservice(request,mid):
    if 'desiid' in request.session:
        pl=Services.objects.get(id=mid)
        pl.delete()
        return redirect("Designer:Add-Services")
    else:
        return redirect('Guest:Login')

def feedback(request):
    if 'desiid' in request.session:
        designerobj=Newdeigner.objects.get(id=request.session["desiid"])
        if request.method=='POST':
            feed=request.POST.get("feedback")
            Feedbackdesigner.objects.create(Feedback=feed,user=designerobj)
            return render(request,'Designer/Home/')
        else:
            return render(request,'Designer/Feedbackdesigner.html')
    else:
        return redirect('Guest:Login')

def complaintdesigner(request):
    if 'desiid' in request.session:
        designerobj=Newdeigner.objects.get(id=request.session["desiid"])
        if request.method=='POST'and request.FILES:
            con=request.POST.get("content")
            att=request.FILES.get("attachment")
            Complaintdesigner.objects.create(content=con,attachment=att,designer=designerobj)
            return redirect('/Designer/Home/')
        else:
            return render(request,'Designer/complaintdesigner.html')
    else:
        return redirect('Guest:Login')

def logout(request):
    del request.session['desiid']
    return redirect('Guest:Login')

def viewcomplaintdesigner(request):
    if 'desiid' in request.session:
        com=Complaintdesigner.objects.filter( designer=request.session["desiid"],vstatus=0)
        return render(request,'Designer/Designercomplaintview.html',{"complaint":com})
    else:
        return redirect('Guest:Login')
        
def viewcomplaintuserdesigner(request):
    if 'desiid' in request.session:
      designerobj=Complaintusertodesigner.objects.all()
      return render(request,'Designer/Viewusercomplaint.html',{"designer":designerobj}) 
    else:
        return redirect('Guest:Login')
    

def replyusertodesigner(request,rdid):
    obj= Complaintusertodesigner.objects.get(id=rdid)
    if request.method=='POST':
        rep=request.POST.get("reply")
        obj.replay=rep
        obj.vstatus=1
        obj.save()
        return redirect('Designer:Complaint Designer')
    else:
        return render(request,'Designer/Replydesigner.html')

Designer/templates/Designer/Changepassword.html
{% extends 'Designer/Head.html' %}


{% block content %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="tab" style="width: 100%;padding-left:100px;">
        <br><br><br><br><br><br>
        <h3 style="padding-left: 500px; "><b>Change Password</b></h3>
    <form method="post">
        <table border="2" width="350px" style="background-color: violet;" align="center">
            <tr style="background-color: rgb(7, 163, 20);">
                <th>Currentpassword</th>
                    <td>
                        <input type="password" name="currentpassword">
                    </td>
            </tr>
            <tr>
                <th>Newpassword</th>
                <td>
                    <input type="password" name="newpassword">
                </td>
            </tr>
            <tr>
                <th>confirmpassword</th>
                <td>
                    <input type="password" name="confirmpassword" onblur="return checkpwd(newpassword,this)">
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" name="btnsave" value="save">
                    <input type="reset" name="btncancel" value="cancel"
                </td>
            </tr>
        </table>
    </form>
</body>
<script>
    
function checkpwd(confirm, pass) {
    if(confirm.value != pass.value){
        alert("password Mismatch")
        return false
    }
    else{
        return true
    }
    }

</script>
</html>
<br><br><br><br><br><br><br><br>
{% endblock %}

Designer/templates/Designer/Complaintdesigner.html
{% extends 'Designer/Head.html' %}


{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div id="tab" style="width: 100%;padding-left:100px;">
        <br><br><br><br><br><br>
        <h3 style="padding-left: 450px; "><b>Designer Complaint</b></h3>
    <form method="post">
        <table border="2" width="350px" style="background-color: violet;" align="center">
 <tr>
            <th>Content</th>
            <td>
                <input type="text" name="content" required autocomplete="off">
            </td>
        </tr>
        <tr>
            <th>Attachment</th>
            <td>
                <input type="file" name="attachment" required autocomplete="off">
            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">
                <input type="submit" name="btnsave" value="save">
                <input type="reset" name="btncancel" value="cancel">
            </td>
        </tr>
    </table>
    </form>
    </div>
</body>

</html>
<br><br> <br><br> <br><br>
{% endblock %}

Designer/templates/Designer/Designercomplaintview.html
{% extends 'Designer/Head.html' %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="tab" style="width: 100%;padding-left:100px;">
        <br><br><br><br><br><br>
        <h3 style="padding-left: 450px; "><b>View Designercomplaint</b></h3>
    <form method="post">
        <table border="2" width="350px" style="background-color: violet;" align="center">

            <tr style="background-color: rgb(7, 163, 20);">
                <th>Date</th>
                <th>Content</th>
                <th>Attachment</th>
                <th>Replay</th>
            </tr>
            {%  for i in complaint %}
            <tr>
                <td>{{i.doc}}</td>
                <td>{{i.content}}</td>
                <td><a href="{{i.attachment.url}}" download>Download</a></td>
                <td>{{i.replay}}</td>
            </tr>
            {% endfor %}
        </table>
    </form>
    </div>
</body>
</html>
<br><br> <br><br> <br><br><br><br> <br><br>
{% endblock %}

Designer/templates/Designer/Head.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description"
		content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Tillage</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="{% static 'Main/assets/img/favicon.png' %}">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/all.min.css' %}">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'Main/assets/bootstrap/css/bootstrap.min.css' %}">
	<!-- owl carousel -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/owl.carousel.css' %}">
	<!-- magnific popup -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/magnific-popup.css' %}">
	<!-- animate css -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/animate.css' %}">
	<!-- mean menu css -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/meanmenu.min.css' %}">
	<!-- main style -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/main.css' %}">
	<!-- responsive -->
	<link rel="stylesheet" href="{% static 'Main/assets/css/responsive.css' %}">
	<!-- form.css -->
	<link rel="stylesheet" href="{% static 'form.css' %}">

</head>

<body>

	<!--PreLoader-->
	<div class="loader">
		<div class="loader-inner">
			<div class="circle"></div>
		</div>
	</div>
	<!--PreLoader Ends-->

	<!-- header -->
	<div class="top-header-area" id="sticker" style="background-color: #051922;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="{% url 'Viewhome' %}">
								<div class="title">
									<p style="font-size:40px; color: brown;">Tillage</p>
								</div>
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li> <a></a></li>
								<li> <a></a></li>
								<li> <a></a></li>
								<li> <a></a></li><li> <a></a></li>
								<li> <a></a></li>
								<li> <a></a></li>
								<li> <a></a></li>
								<li> <a></a></li>
								<li> <a></a></li>
								
								<li class="current-list-item"><a href="{% url 'Designer:Designer-Home' %}">Home</a>
									<!-- <ul class="sub-menu">
										<li><a href="index.html">Static Home</a></li>
										<li><a href="index_2.html">Slider Home</a></li>
									</ul> -->
								</li>
								<!-- <li><a href="{% url 'Guest:Login' %}">Login</a></li> -->
								<li><a href="">Privacy</a>
									<ul class="sub-menu">
										<li><a href="{%  url 'Designer:my-profile' %}">Myprofile</a></li>
										<li><a href="{%  url 'Designer:edit-profile' %}">Editprofile</a></li>
										<li><a href="{%  url 'Designer:change-password' %}">Changepassword</a></li>

									</ul>
								</li>
								<li><a href="">services</a>
									<ul class="sub-menu">
										<li><a href="{%  url 'Designer:Add-Services' %}">Add services</a></li>

									</ul>
								</li>
								<li><a href="{%  url 'Designer:Feedback Designer' %}">Designer Feedback</a></li>
								<li><a href="">Complaints</a>
									<ul class="sub-menu">
										<li><a href="{%  url 'Designer:Viewcomplaint Designer' %}">Designer
												Complaint</a></li>
										<li><a href="{%  url 'Designer:Viewcomplaint user' %}">User Complaint</a></li>
										<li><a href="{%  url 'Designer:Complaint Designer' %}">Send Complaint</a></li>

									</ul>
								</li>
								<li><a href="{%  url 'Designer:logout' %}">Logout</a></li>

							</ul>
						</nav>


						<!-- <a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div> -->
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->

	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search area -->
	

	{% block content %}


	{% endblock %}

	<!-- footer -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-box about-widget">
						<h2 class="widget-title">About us</h2>
						<p>Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit voluptatem accusantium
							doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box get-in-touch">
						<h2 class="widget-title">Get in Touch</h2>
						<ul>
							<li>34/8, East Hukupara, Gifirtok, Sadan.</li>
							<li>support@fruitkha.com</li>
							<li>+00 111 222 3333</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box pages">
						<h2 class="widget-title">Pages</h2>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><a href="services.html">Shop</a></li>
							<li><a href="news.html">News</a></li>
							<li><a href="contact.html">Contact</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box subscribe">
						<h2 class="widget-title">Subscribe</h2>
						<p>Subscribe to our mailing list to get the latest updates.</p>
						<form action="index.html">
							<input type="email" placeholder="Email">
							<button type="submit"><i class="fas fa-paper-plane"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end footer -->

	<!-- copyright -->
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<p>Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>, All Rights
						Reserved.<br>
						Distributed By - <a href="https://themewagon.com/">Themewagon</a>
					</p>
				</div>
				<div class="col-lg-6 text-right col-md-12">
					<div class="social-icons">
						<ul>
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end copyright -->

	<!-- jquery -->
	<script src="{% static 'Main/assets/js/jquery-1.11.3.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'Main/assets/bootstrap/js/bootstrap.min.js' %}"></script>
	<!-- count down -->
	<script src="{% static 'Main/assets/js/jquery.countdown.js' %}"></script>
	<!-- isotope -->
	<script src="{% static 'Main/assets/js/jquery.isotope-3.0.6.min.js' %}"></script>
	<!-- waypoints -->
	<script src="{% static 'Main/assets/js/waypoints.js' %}"></script>
	<!-- owl carousel -->
	<script src="{% static 'Main/assets/js/owl.carousel.min.js' %}"></script>
	<!-- magnific popup -->
	<script src="{% static 'Main/assets/js/jquery.magnific-popup.min.js' %}"></script>
	<!-- mean menu -->
	<script src="{% static 'Main/assets/js/jquery.meanmenu.min.js' %}"></script>
	<!-- sticker js -->
	<script src="{% static 'Main/assets/js/sticker.js' %}"></script>
	<!-- main js -->
	<script src="{% static 'Main/assets/js/main.js' %}"></script>

</body>

</html>

Designer/templates/Designer/Homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hii</h1>
    <a href="{%  url 'Designer:my-profile' %}">My Profile</a>
    <a href="{%  url 'Designer:edit-profile' %}">edit Profile</a>
    <a href="{%  url 'Designer:change-password' %}">change password</a>
    <a href="{%  url 'Designer:Add-Services' %}">Add Services</a>
    <a href="{%  url 'Designer:Feedback Designer' %}">Designer Feedback</a>
    <a href="{%  url 'Designer:Viewcomplaint Designer' %}">Viewmy complaints</a>
    <a href="{%  url 'Designer:Viewcomplaint user' %}">Viewuser complaints</a>
    <a href="{%  url 'Designer:Complaint Designer' %}">Send complaints</a>
    <a href="{%  url 'Designer:logout' %}">Logout</a>
</body>
</html>

Designer/templates/Designer/Newservices.html
{% extends 'Designer/Head.html' %}


{% block content %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
         function nameval(elem) {
            console.log("Haii")
            var emailexp = /^([A-Za-z ]*)$/;
            if (elem.value.match(emailexp)) {
                document.getElementById("name").innerHTML = "";
                return true;
            }
            else {

                document.getElementById("name").innerHTML = "<span style='color: red;'>Alphabets Are Allowed</span>";
                elem.focus();
                return false;
            }
        }
        function emailval(elem) {
            var emailexp = /^([a-zA-Z0-9.\_\-])+\@([a-zA-Z0-9.\_\-])+\.([a-zA-Z]{2,4})$/;
            if (elem.value.match(emailexp)) {
                document.getElementById("email").innerHTML = "";
                return true;
            }
            else {

                document.getElementById("email").innerHTML = "<span style='color: red;'>Check Email Address Entered</span>";;
                elem.focus();
                return false;
            }
        }
        function checknum(elem) {
            var numericExpression = /^[0-9]{8,10}$/;
            if (elem.value.match(numericExpression)) {
                document.getElementById("contact").innerHTML = "";
                return true;
            }
            else {
                document.getElementById("contact").innerHTML = "<span style='color: red;'>10 Numbers Only Allowed</span>";
                elem.focus();
                return false;
            }
        }
        
    </script>
</head>
<body>
    <br>
    <div id="tab" style="width: 100%;padding-left:100px;">
        <br><br><br><br><br><br>
        <h3 style="padding-left: 550px; "><b>Add Services</b></h3>
    <form method="post">
        <table border="2" width="350px" style="background-color: violet;" align="center">

            <tr>
                <th>Modelname</th>
                <td>
                    <input type="text" name="modelname" placeholder="Enter Name" autocomplete="off" required
                    onkeyup="nameval(this)">
                <div id="name"></div>
                </td>
            </tr>
            <tr>
                <th>Rate</th>
                <td>
                    <input type="text" name="rate" placeholder="Enter rate" required autocomplete="off" pattern="[0-9]{1-10}">
                </td>
            </tr>
            <tr>
                <th>Details</th>
                <td>
                    <input type="text" name="details" required autocomplete="off">
                </td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>
                    <input type="file" name="photo" required autocomplete="off">
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" name="btnsubmit" value="submit">
                    <input type="reset" name="btnreset"  value="cancel">
                </td>
            </tr>
        </table>
        <br>
        <hr>
        <br>
        <table border="1" align="center">
            <tr>
                <th>Name</th>
                <th>Rate</th>
                <th>Details</th>
                <th>Photo</th>
            </tr>
            {% for x in name %}
            <tr>
                <td>{{ x.name}}</td>
                <td>{{ x.rate }}</td>
                <td>{{ x.details}}</td>
                <td><img src="{{x.logo.url}}" width="120" height="120"></td>
                
                <td><a href="{% url 'Designer:del-Services' x.id %}">Delete</a></td>
            </tr>
            {% endfor %}
    </form>
</div>
</body>
</html>
<br><br><br><br><br><br><br><br>
{% endblock %}